### PR TITLE
Releases screens > Verify your info > phone number lines

### LINKED ISSUE #2476: Releases screen - contact info - phone numbers
- [ ] Each phone number should be on a new line

screen shot 2018-01-24 at 11 31 01 am

### PR DESCRIPTION
**Pull request by floresj**
Resolves #2476. Just wrapped in div so they render on new line.

### CODE REVIEW

**Comment by bmallred** [comment]
image

**Comment by bmallred** [comment]
@floresj can you pull this down and make double check nothing crazy with "normal" checkboxes is going on. I did a visual check as well and didn't see anything.

Problem was the time of day checkboxes had a `z-index: -1` being applied to them and I know this issue keeps cropping up from time to time.

**Comment by floresj** [comment]
@bmallred sure thing :+1:

**Comment by floresj** [comment]
Validating normal checkboxes

selection_752
selection_751
selection_750

**Comment by floresj** [comment]
selection_753

**Pull request merged**
