### PR TITLE
Do not allow end date before start date for treatments

### PR DESCRIPTION
**Pull request by bmallred**
Issue: #919

## Preview

screen shot 2017-06-23 at 10 42 38 am

Instead of passing error state downwards the error is applied at the composite component and visually managed through styles.

### CODE REVIEW

**Comment by floresj** [comment]
Validating as exected :+1: 

selection_232

**Comment by bmallred** [comment]
@floresj got one changing coming down range so hold off merging please!

**Comment by bmallred** [comment]
@floresj k committed, thanks!

**Comment by floresj** [comment]
@ Sounds bueno!

**Comment by floresj** [comment]
@bmallred Were you going to push more date things here?

**Comment by bmallred** [comment]
@floresj nope, i have another branch for the remaining ones!

**Pull request merged**
