### PR TITLE
Financial accordion item validation

### LINKED ISSUE #1807: Accordion Item Validation - Financial Record

### PR DESCRIPTION
**Pull request by floresj**
Resolves #1807.
- Normalized components to use `name="Item"`.
- If an accordion had multiple fields, move those fields into a separate component.

### CODE REVIEW

**Comment by bmallred** [comment]
image

Missing the message on first rendering. This is happening to a number of the accordions.

**Comment by bmallred** [comment]
image

The review error message is not being displayed on the first rendering for accordions

**Comment by bmallred** [comment]
Just that one fix and I think we are good!

**Comment by floresj** [comment]
I pulled from master again and ran it and didn't run into any issues logging in. I now see the error message showing up on initial load. Let me know if you're still havin' issues.

**Pull request merged**
