### PR TITLE
Making accordion placeholder text italic

### PR DESCRIPTION
**Pull request by Jay-Neighbours-I72**
Adding italics

### CODE REVIEW

**Comment by floresj** [comment]
We'll have to be sure we're using `i18.m()` and not `i18.t()` for the summary text so it shows up properly. I took a quick glance and some of them are using the plain text one.

**Comment by floresj** [comment]
@bmallred Just did a quick test and after switching from text to markdown, it renders like the following:

selection_296

That's seems to occur because the markdown surrounds the content in a `<div></div>`. When I set the div to `display: inline-block`, (inside of Accordion.scss around line 235 for everything under `.left` css class) it appears to line up properly.

selection_298

Cool if I make these code updates?

**Comment by bmallred** [comment]
@floresj we good to merge this?

**Comment by floresj** [comment]
@bmallred Yessir if it's all good with you.

**Pull request merged**
