### PR TITLE
Substance Use - Ordered accordion summary update

### LINKED ISSUE #1460: Substance use - order of questions creates unhelpful treatment nickname
Normally the accordion nickname is the drug in question. In this case, the treatment accordion title is the entity that ordered treatment, not the drug.

https://eqip-prototype-staging.fr.cloud.gov/form/substance/drugs/ordered

Maybe not a bug? but a departure from what we do elsewhere on the form.

screen shot 2017-06-19 at 2 11 13 pm

### PR DESCRIPTION
**Pull request by floresj**
Resolves #1460 

`form/substance/drugs/ordered`

### CODE REVIEW

**Comment by bmallred** [comment]
Did something similar need to happen for `/form/alcohol/ordered`?

cc: @floresj @Jay-Neighbours-I72

**Comment by bmallred** [comment]
## /form/drugs/ordered

image

**Comment by floresj** [comment]
Good question. For that particular page, it could vary based on their response. If they select no to the second question, we can render the explanation

selection_265

If they click yes, we could render the counselor/treatment provider

selection_266

cc: @bmallred @Jay-Neighbours-I72

**Comment by bmallred** [comment]
@floresj thinking of pushing this through and if we need to make a change to the other section we'll do that then.

**Pull request merged**
