### PR TITLE
Update DateControl and DateRange to highlight entire date on some errors

### PR DESCRIPTION
**Pull request by bmallred**
Issue: #1457 

If the date control or range has an error which concerns the entire date then we want to ensure the entire date is highlighted and not just an individual component.

### CODE REVIEW

**Comment by floresj** [comment]
Sir, is this one good to review?

**Comment by bmallred** [comment]
Sure thing. Was just looking at test coverage.

**Comment by floresj** [comment]
### DateControl validation
selection_240
selection_239
selection_238

**Comment by floresj** [comment]
### DateRange control
selection_243
selection_242
selection_241
selection_245
selection_244

**Pull request merged**
