### PR TITLE
Help text removal

### PR DESCRIPTION
**Pull request by Jay-Neighbours-I72**
Removing unnecessary help text from the Emotional health section

### CODE REVIEW

**Comment by floresj** [comment]
Go @Jay-Neighbours-I72 with the commit fest!

**Comment by billy22g** [comment]
@floresj @bmallred Should we also be removing the help text entirely when we're removing these lines? For example, here: https://github.com/truetandem/e-QIP-prototype/blob/master/src/config/locales/en.js#L5197

cc: @Jay-Neighbours-I72

**Comment by floresj** [comment]
That would be good to do. There's no need to keep unused code!

**Comment by bmallred** [comment]
@billy22g we definitely can although I don't think we have been. Probably need to write a script to help identify localisations not used.

**Comment by Jay-Neighbours-I72** [comment]
A script to remove all the unused text is a great idea.

Maybe we wait until each section help text is final approved first? In case we need to put help back on any inputs?

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 that is fine. How does that sound @billy22g about waiting until approval on the help verbiage?

**Comment by billy22g** [comment]
Cool with me!

**Pull request merged**
