### PR TITLE
Previously used address in sections referenced in R&D

### PR DESCRIPTION
**Pull request by bmallred**
Issue: #1674

In order to access previously used address the `Location` component must be passed the following:

 - `dispatch()`: this is the `redux` dispatcher allowing `Location` to update the address book(s)
 - `addressBooks`: An object from `redux` where each property name is an individual address book
 - `addressBook`: The address book name (**example**: *Court, Relative, ForeignNational, etc.*)

### CODE REVIEW

**Comment by floresj** [comment]
## And we have an address book
selection_405

**Comment by floresj** [comment]
Showing empty address book 
selection_406

Showing an entry in the book
selection_409

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 the screenshot @floresj posted above when there are no addresses in the address book... should we

 1. not display the link for the address book
 2. display a different message when they open it
 3. leave it as is

**Comment by floresj** [comment]
Reviewed with Allred :+1:

**Pull request merged**
