### PR TITLE
WIP: Rough draft of CircleCI configuration file

### PR DESCRIPTION
**Pull request by bmallred**

### CODE REVIEW

**Comment by ctro** [comment]
This makes sense to me.  I think we may have to pick this work up for the incoming sprint.   GSA is losing Travis for Circle soon.

**Comment by ctro** [comment]
Also, @bmallred have we tried running this on circle yet?
If yes can you share a url?
If not, let me know if you need any assistance.

**Comment by bmallred** [comment]
@ctro negative. Just threw this PR in the **In Progress** swim lane with top priority

**Comment by ctro** [comment]
Thanks @bmallred.  Also cc @pjsumm 
I think the Travis -> Circle work needs to happen soon, but I don't think it has to trump everything in the sprint.  I just looked at the Travis/18F page and there are another 50 18f projects still on Travis.

Yes, the deadline was yesterday.  One thing I've learned is that "deadline" has a different meaning in Gov. ;)

**Comment by bmallred** [comment]
@ctro not worried! I'll squash them at the end to make it look like I don't have any fatigue setting in :-)

**Pull request merged**
