### PR TITLE
Limit external references

### PR DESCRIPTION
**Pull request by bmallred**
External references were the following:

 - [x]: html5shiv.min.js
 - [x]: respond.min.js
 - [x]: dap.min.js

These are stored in `lib/` either statically or on-demand. When `gulp` compiles the front-end code it will place these in the `dist/` directory.

Resolves:  truetandem/e-QIP-prototype#2632

### CODE REVIEW

**Comment by floresj** [comment]
When I looked at the resource, it looks like `dap.min.js` contains html  content and not javascript. 

selection_758

**Comment by bmallred** [comment]
@floresj mine is JavaScript... If its HTML that looks like our site it is because you need to rebuild the frontend.

```sh
make build-react
```

**Comment by floresj** [comment]
I tried  `docker-compose build` initially. But using build-react did the trick. 👍

**Comment by bmallred** [comment]
Ah thought I had changed the compose config as well... Oops my bad!

**Pull request merged**
