### PR TITLE
Added two paragraphs to contact information

### PR DESCRIPTION
**Pull request by bmallred**
Issue #513 

Added two paragraphs to the contact information section

## Preview

contact-new-verbiage

### CODE REVIEW

**Comment by billy22g** [comment]
Hmmm...aren't we only starting with two phone numbers? If so, it makes the verbiage confusing "Provide three phone numbers." Not sure if those are considered instructions or "the question." cc: @jehlers

**Comment by jehlers** [comment]
Yeah, good catch @billy22g. It's definitely on the line if we are getting that text from the content guide. I'd propose changing it to "Provide at least two phone numbers (one is required)." Or something like that. This is something to pass by Donna.

**Comment by billy22g** [comment]
cc: @Jay-Neighbours-I72 on the above proposed change and change guide for Donna.

**Comment by Jay-Neighbours-I72** [comment]
Adding this to the SF86 Potential content updates google doc.

**Pull request merged**
