### PR TITLE
Accordion default state updates

### LINKED ISSUE #1256: Accordion - review screen - all accordion items
- [ ] On review screen - all accordion items should load closed (Currently they are all open)

### PR DESCRIPTION
**Pull request by floresj**
Resolves #1256. All accordions start out closed when accessed via a review section.

### CODE REVIEW

**Comment by bmallred** [comment]
Missed accordions:

 - `/form/citizenship/multiple`
    - Have you ever been issued a passport (or identity card for travel) by a country other than U.S.? **Yes**
      - Have you eve used this passport (or identity card) for foreign travel? **Yes**
 - `/form/military/foreign`
    - Do you maintain contact with current or former associates, colleagues, or acquaintances from your service in this organization? **Yes**

**Comment by bmallred** [comment]
The navigation (next, back, etc.) in the **Foreign activities** section is all over the place. Can you normalize this as well?

**Comment by floresj** [comment]
:+1: :+1: will do.

**Comment by bmallred** [comment]
@floresj I'm not sure this addresses what @billy22g was referencing in #1321 

> My interpretation is that if you leave a section with accordions and then come back, that they should be closed. Currently, e.g. Your History, if you fill out a couple, leave, then come back, all the accordions are open which is very confusing.

I believe he is stating this is suppose to happen outside of the **review** sections as well **if the section has already been visited**. This was behavior we had at one point early on then was removed for one of the usability testings (I'm pretty sure it goes back to testing of the accordion v2).

**Comment by floresj** [comment]
@bmallred Thanks for clarifying that! I'll tackle that in a separate PR. I'll follow up with some more questions in issue #1321.

**Pull request merged**
